version: '3'
services:
  sqs-insight:
    image: realies/sqs-insight
    environment:
      - mode=dynamicEndpoint
      - region=us-east-1
      - url=http://elasticmq:9324/
    command: ["/wait-for", "elasticmq:9324", "-t", "30", "--", "/init.sh"]
    volumes:
      - ./wait-for:/wait-for
    ports:
      - 3000:3000
    depends_on:
      - elasticmq
  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      - ./conf/elasticmq.conf:/opt/elasticmq.conf
    ports:
      - 9324:9324
